### ISSUE TITLE
[MKT-55-23] Add blog to https://blog.yearn.finance/ or medium

### ISSUE THREAD

**Issue by kishvdd** [yearn/yearn-marketing#23]
Ghosty are you able to help with this? Could you add this blog (or it’s contents) to the yearn blog, or medium?

[https://kishvd.medium.com/my-first-impressions-of-being-a-contributor-at-yearn-e154743b9cd5](https://kishvd.medium.com/my-first-impressions-of-being-a-contributor-at-yearn-e154743b9cd5)

**Comment by DarkGhost7** [comment]
Sure will do

**Comment by DarkGhost7** [comment]
https://github.com/yearn/yearn-comms/issues/1079

**Comment by kishvdd** [comment]
Hey, was this added?

**Comment by qosmonot** [comment]
published:

https://blog.yearn.finance/articles/kish/my-first-impressions-at-yearn

translations in Portuguese and Turkish already up

**Comment by qosmonot** [comment]
this was added, yes 
https://blog.yearn.finance/articles/kish/my-first-impressions-at-yearn
