### ISSUE TITLE
[MKT-61-27] Do a Chinese version of video: How yvVaults work?

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#27]
Working with Bee on this one:

* Send English script
* Translate content (text) to Chinese
* Create voice-over in Chinese
* Edit video with Chinese content

[https://user-images.githubusercontent.com/88235023/158272775-243b8c82-c556-4cad-8d5e-1e81c9062df5.mp4](https://user-images.githubusercontent.com/88235023/158272775-243b8c82-c556-4cad-8d5e-1e81c9062df5.mp4)

**Comment by Bee926** [comment]
James, did you want audio from 2 different people? 

Since I see in the original video (the English version) it has a dude and a female. :)

Me and Xiaona are both female though. Not sure if that could cause a problem. Let me know.

**Comment by JKtranslator** [comment]
No problem. Will adjust the video accordingly.

**Comment by JKtranslator** [comment]
No problem. I will adjust the videos accordingly. Thanks

Em ter., 15 de mar. de 2022 16:54, Bee926 ***@***.***>
escreveu:
