### ISSUE TITLE
[MKT-67-33] Brazil Web3 Community Growing

### ISSUE THREAD

**Issue by MarcoWorms** [yearn/yearn-marketing#33]
Meetup events and now Universities outreach as well.

I'm doing it in Brazil, if anyone is doing this elsewhere let's share experiences!

**Comment by MarcoWorms** [comment]
The meetups I did virtually and were separate from the universities initiative

I'm making it a DeFi/Web3/DAOs event where I talk to the students and see what they think it's nice, atm I offer what I can personally help with like:

- A presentation about intro to defi web3 daos
- Help setting up events virtual or physical since I know how to help with both

The main idea behind the initiative is to grow crypto culture and show that Yearn and other DAOs exist in this universe, so in long-term many people in the tech field will know about us and when they feel technically ready they can apply to roles!

**Comment by JKtranslator** [comment]
Do You want help to polish/create content? (video, infographic, etc)?
