### ISSUE TITLE
[MKT-70-36] Simplify complex information: Create an infographic about how Yearn calculates estimated returns apy

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#36]
Despite the excellent article Marco wrote about the topic, there are still doubts about how Yearn calculates the APY on the vaults. Let's make the explanation more visual, to help the overall understanding of the topic

A conversation about the topic started here: [https://t.me/c/1342328428/8371](https://t.me/c/1342328428/8371)

Resources: [https://medium.com/coinmonks/lido-curve-yearn-and-zapper-how-should-you-stake-your-eth-44ac2aa38e55](https://medium.com/coinmonks/lido-curve-yearn-and-zapper-how-should-you-stake-your-eth-44ac2aa38e55)\
[https://medium.com/iearn/how-yearn-calculates-estimated-returns-apy-b4fd5b687bf9](https://medium.com/iearn/how-yearn-calculates-estimated-returns-apy-b4fd5b687bf9)

**Comment by JKtranslator** [comment]
File for review 
![Yearn APY](https://user-images.githubusercontent.com/88235023/159140323-8c8729e6-f830-4427-8106-bd88b47a4b9d.png)

**Comment by DarkGhost7** [comment]
For non-curve assets: when you say Net APY. I would say `Net APY: Vault's current APY after all fees, usually shows Monthly APY`
Not sure if this matters though. Currently net apy is showing monthly but it has in the past showed weekly I think on fantom though it seems like they recently switched that back to monthly again. Other than that which does really have to be changed it looks good to me! Great job

**Comment by DarkGhost7** [comment]
Maybe we can also say for non-curve vaults we use past performance annualized as apy calculation, and for curve vaults we use fwd-looking apy calculations based on curve's calculations and curve emissions.

**Comment by JKtranslator** [comment]
Made the changes and also a new version with a pallete more aligned with Yearn v2 Figma 
![Yearn APY 1](https://user-images.githubusercontent.com/88235023/160381284-f7c22417-62a8-46ca-b025-1655228e44f2.png)
![Yearn APY](https://user-images.githubusercontent.com/88235023/160381291-acde795a-ff8e-4f20-83ce-0cccee917f98.png)

**Comment by DarkGhost7** [comment]
Looks good to me @JKtranslator 🚢 it

**Comment by DarkGhost7** [comment]
@bluewillow870 please close
