### ISSUE TITLE
[MKT-72-38] Spanish version of video: How yvVaults work?

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#38]
Working with Lalo on this one:

* Send English script
* Translate content (text) to Spanish
* Create voice-over in Spanish
* Edit video with Spanish content

**Comment by JKtranslator** [comment]
Video made.
Sent to translators channel and Lalo and Mike are reviewing eventual changes.

**Comment by SergioRoVar** [comment]
Hi, please let me know if i can help in something with this task. First time here.
