### ISSUE TITLE
[Medium Article] Top Tips for Contributing at Yearn

### ISSUE THREAD

**Issue by bluewillow870** [yearn/yearn-marketing#45]
Purpose: Create an article around top tips for contributing at Yearn
Draft: https://hackmd.io/@Kish/HkItPe7Z9/edit

**Comment by kishvdd** [comment]
questions are with the contributors, as responses come in will add to blog draft

**Comment by kishvdd** [comment]
received a majority of replies, waiting on one more tomorrow, talking to Loki at 12 pm central. feel like it is in a good place for review.

**Comment by kishvdd** [comment]
shared with marketing group just now for review

**Comment by kishvdd** [comment]
@DarkGhost7 @bluewillow870 would you mind reviewing? i think we could make this public on the blog this week if yall sign off on it. https://hackmd.io/@Kish/HkItPe7Z9/edit

**Comment by kishvdd** [comment]
published: https://kishvd.medium.com/tips-for-new-contributors-4e978d6b73d

**Comment by kishvdd** [comment]
published: https://kishvd.medium.com/tips-for-new-contributors-4e978d6b73d

**Comment by kishvdd** [comment]
Hey @0xWeaver, when you are back would you be able to add me as an author on Yearn's medium? then this will show up on there. Hope vaca is well!

**Comment by 0xWeaver** [comment]
done!

**Comment by kishvdd** [comment]
thanks ser!

**Comment by 0xWeaver** [comment]
https://medium.com/iearn/tips-for-new-contributors-4e978d6b73d

**Comment by kishvdd** [comment]
Thanks!! 🔥🔥
