### ISSUE TITLE
[Article] Contributing at Yearn

### ISSUE THREAD

**Issue by bluewillow870** [yearn/yearn-marketing#46]
Description: Article on how to contribute at Yearn and why

Draft: https://docs.google.com/document/d/132hKMEYXcxptOdTvDUZS0_VnqUlE1fjNhEduNUu1bJ8/edit?usp=sharing

**Comment by kishvdd** [comment]
feel like this is at a good place for review!

**Comment by kishvdd** [comment]
@bluewillow870  what did you think of this one?
