### ISSUE TITLE
[MKT-90-59] Spanish Translation of "The Blue Pill"

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#59]
Translation source: [https://github.com/yearn/yearn-comms/blob/english/public/_posts/_articles/the-blue-pill/es.md](https://github.com/yearn/yearn-comms/blob/english/public/_posts/_articles/the-blue-pill/es.md)\
File edited and sent to Pentacle to upload at [yfistory.org](http://yfistory.org).

**Comment by gingerheart86** [comment]
Hello.
I'm a spanish native speaker.
I see it's already been translated or am I wrong?
How can I help?

**Comment by JKtranslator** [comment]
Hello, it is translated. Now it is waiting to be published at yfistory.org.
