### ISSUE TITLE
[MKT-95-64] Simplify complex information: #DeFiMadeSimple: Folding

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#64]
Proposition: To create an infographic showing all steps needed to perform a Folding Strategy and then show the benefits of using the yVault for it.

Resources: [https://docs.tetu.io/tetu-io/yield-farm/strategies/folding-strategies](https://docs.tetu.io/tetu-io/yield-farm/strategies/folding-strategies)

[https://www.youtube.com/watch?v=kXeEJMW08pI](https://www.youtube.com/watch?v=kXeEJMW08pI)

Objectives:

Explain what the Folding yield farming is\
To highlight the benefits of using yVaults (Less manual work; gas savings; Optimization between strategies to get the best yield; etc)

![](https://uploads.linear.app/71c58dc2-224e-40a9-b4c0-5ae717f1e931/a479c229-9372-4372-998a-148543cbe199/0ddb7e92-5c4f-4253-a8de-6134a8e0b8d0)

**Comment by djgano** [comment]
Love the angle here and think you did a fantastic job with this.
I had a couple design comments on the lower section (see image below).
1) I'd move the rocket ship to the right side of the text.
2) I'd make the logo circle in the upper left smaller, so the center circle gets more relative focus
3) The origami crown image is overlapping the "FOLDING AUTOMATED"
There are a number of alignment issues with the paragraphs and their headers in the lower section. Needs consistency.
<img width="1037" alt="InfoG_feedback copy" src="https://user-images.githubusercontent.com/102051251/162449883-3d0e5ecc-5743-431d-849d-c0eb941f3b65.png">

**Comment by pentcle** [comment]
regarding the design - you can find the yearn mini brand guidelines here. 
https://github.com/yearn/yearn-assets/tree/master/press-kit

we're in the process of rebranding (brand strategy, design language), so aiming to keep all branded materials extremely vanilla (ie unopinionated visuals) until the brand is defined – or use the Blue Pill style creative direction. 
yfistory.org

We can get draper to look at the copy for brand tone of voice.

**Comment by JKtranslator** [comment]
I will redo it with the fonts/colors from the guide and we can take it from there. No Figma file, I can upload it there if needed/wanted.

**Comment by MarcoWorms** [comment]
looks great, I think I'd make it explicit that these are linear steps by adding a number or arrows (did a cheap version here)

![image](https://user-images.githubusercontent.com/7863230/162510190-0cd54311-d018-4284-ba99-9131969a8adc.png)

nice work!!!

**Comment by JKtranslator** [comment]
Changes applied:
![Defi Made Simple_Folding](https://user-images.githubusercontent.com/88235023/163497121-972c4ee4-116b-4b2e-8824-02ac76ab7456.png)
