### ISSUE TITLE
[MKT-123-99] Article Zap Deposits Yearn Finance

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#99]
An article highlighting the benefits of using ZAP (faster, easier and cheaper)

[https://docs.google.com/document/d/1_-FVj-4GCuJmaA9Zk13gm83pKWIAy3ZPkY7erJ2T0Po/edit?usp=sharing](https://docs.google.com/document/d/1_-FVj-4GCuJmaA9Zk13gm83pKWIAy3ZPkY7erJ2T0Po/edit?usp=sharing)

**Comment by 101717** [comment]
Hey there! I've just added a few comments :) 
Overall that's a very detailed walkthrough, thanks a lot for making it!
